language: elixir

elixir:
  - 1.6
  - 1.5
  - 1.4

otp_release:
  - 21.0
  - 20.3
  - 19.3

matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 21.0

script:
  - mix credo -a
  - mix test

notifications:
  recipients:
    - tobsve03@gmail.com
